### ISSUE TITLE
Keymapper slows the speed of typing

### ISSUE THREAD

**Issue by ibdknox** [joshuafcole/keymapper#5] opened 2014-01-29 18:57 UTC
Because you're listening directly to changes on the keymap and not debouncing/throttling, anything that causes tags to change will force the UI to re-render even if it's not shown. That's probably a reasonable tact to take as long as the tab is open, but if it's not, there should be no impact on performance.

**Comment by joshuafcole** [comment] 2014-02-01 07:00
Having a lot more trouble getting this working with debouncing than I expected. Apparently bound and lt.util.js/debounce don't play nicely together. My intuition suggests that's because debounce uses setTimeout, so results are asynchronous instead of returned. As a simple reproduction:

``` clojure
(defui keymap-panel [this]
  [:div {:id "keymapper"}
   [:h1 "Keymapper" ]
   [:ul (bound
         keyboard/key-map
         ;(util/debounce
         ; 100
          #(for [[k v] %] (keymap-item this [k v]))
          )]])
```

Works, whereas

``` clojure
(defui keymap-panel [this]
  [:div {:id "keymapper"}
   [:h1 "Keymapper" ]
   [:ul (bound
         keyboard/key-map
         (util/debounce
          100
          #(for [[k v] %] (keymap-item this [k v]))
          ))]])
```

does not. Any suggestions on a better implementation to use here, @ibdknox? The slowdown is much more serious than I realized and if I can't get this resolved shortly I'd rather pull the plugin from the repository than have people seeing an invisible horrible slowdown in their LT experience.

Thanks,
Josh

**Comment by ibdknox** [comment] 2014-02-02 17:07
One simple solution would be to check if you're active before trying to render anything. (in your show set ::active, in your close set it to false). That will probably fix the immediate issue. The longer term solution would probably be to not use bound and instead watch the atom directly for changes and then tell your thing to update. That'll give you more control over when/how/etc all this goes down.

**Comment by joshuafcole** [comment] 2014-04-03 17:25
Resolved via PR courtesy of @ibdknox

**Closed as completed by joshuafcole** 2014-04-03 17:25 UTC
